### ISSUE TITLE
Rename repository to advanced_search

### ISSUE THREAD

**Issue by ghost** [GMS-SA/roundcube-advanced-search#1]
Please rename the repository to advanced_search, otherwise using the plugin will result in following error: [31-Jan-2013 23:23:20 +0100]: PHP Error: Failed to load plugin file /mail/plugins/advanced_search/advanced_search.php in /mail/program/lib/Roundcube/rcube_plugin_api.php on line 217

**Comment by gms-chris** [comment]
We have updated the README with checkout and install instructions.
Renaming of the repository is not going to happen. The repository name "advanced_search" is not descriptive enough. Also, using the GitHub ZIP download, would still have naming issues as GitHub dynamically names the directory in the ZIP based on the project and branch.

The updated instructions should make it clear how to perform the installation correctly.
