### ISSUE TITLE
Russian localization and some other issues

### ISSUE THREAD

**Issue by urusha** [GMS-SA/roundcube-advanced-search#10]
Here is the russian localization.
https://gist.github.com/urusha/9185215

Also, it would be nice to make criteria translatable (for now we have to edit config.inc.php).

Another issue is in the screenshot (Roundcube 1.0-rc, advanced_search 2.1.2, "Show mailbox title as column" is enabled)
![cols](https://f.cloud.github.com/assets/1746504/2244657/9a9a6588-9d41-11e3-9516-98ea67a889bc.png)

Thanks for the plugin.

**Comment by FireFoxIXI** [comment]
@urusha Thanks for your feedback and your translation. 

As for the screenshot, indeed in Roundcube 1.0 the html structure changed slightly, so we will need to adapt to this.

As for making the criteria translatable, we will have a look into that.

**Comment by FireFoxIXI** [comment]
@urusha we found a way to make the criteria translatable. 

I forked your russian localization (  https://gist.github.com/FireFoxIXI/9190041 ) and added the additional labels.

Could you please review/complete this gist so we can include those translations in the next update?

Thanks

**Comment by urusha** [comment]
Here is modified gist: https://gist.github.com/urusha/9190524
I think there should be additional label for "Saved searches:", a nice russian translation for it would be "Сохраненные".

Also, despite there is no classic skin support, it mostly works, except toolbar button:
![2014-02-24 20 28 45](https://f.cloud.github.com/assets/1746504/2247707/1a444644-9d71-11e3-9267-6799b5e5e26d.png)
... and "Show mailbox title as column" - it doesn't work at all.

Taking the opportunity, I'd like to request another feature: it would be really nice to have an ability to view saved searches as virtual folders. 

Thanks.

**Comment by FireFoxIXI** [comment]
@urusha Thanks for your feedback, much appreciated.

I integrated your translation and added a label for "Saved searches".

I also added basic classic support, most of the issues were just missing css.

Will need to do some more test before publishing.

**Comment by FireFoxIXI** [comment]
@urusha could you please check that everything works as expected, if so i will close this issue.

Thanks

**Comment by urusha** [comment]
I've checked recent stable version:
- classic skin looks fine now
- rows and cols mbox names look fine too with rc1.0
- translations seem to work fine, but I found a few more labels to translate:
  - in "save search" menu: Name = Название, Save = Сохранить, Cancel = Отмена
  - with "Show mailbox title as column" Mbox = Ящик
- "advanced search" now takes first place in settings menu, I think it's better to move it to the end of the list, since it's really not the main thing users would like to setup.

Thank you so much for your work!

**Comment by FireFoxIXI** [comment]
@urusha Thanks again for your support. 

All this, except the virtual folders has been added to the latest stable version.
For the virtual folders i added a new feature request under #12
