### ISSUE TITLE
graphical awareness that search is still `loading`

### ISSUE THREAD

**Issue by cusco** [GMS-SA/roundcube-advanced-search#11]
Hi,

There should be a visual information, indicating that the search is still performing... It can take quite a while to display results (I guess I really have many folders and all...) and meanwhile it just shows blank message list...

**Comment by FireFoxIXI** [comment]
@cusco thanks for your input. 
A loading indicator has been added to the latest stable version.

**Comment by cusco** [comment]
awsome, thank you
