### ISSUE TITLE
Don't know how to conntact or push my translation.

### ISSUE THREAD

**Issue by dzikus** [GMS-SA/roundcube-advanced-search#13]
I don't know how to contact you or push my commit with Polish translation so i attach it here:
<?php
    $labels = array();
    $labels['in'] = 'w';
    $labels['and'] = 'i';
    $labels['or'] = 'lub';
    $labels['not'] = 'nie';
    $labels['where'] = 'gdzie';
    $labels['exclude'] = 'wyklucz';
    $labels['andsubfolders'] = 'i podfolderach';
    $labels['allfolders'] = 'Wszystkie foldery';
    $labels['advancedsearch'] = 'Wyszkuiwanie zaawansowane';
    $labels['label_display_options'] = 'Opcje w zaawansowanych wynikach wyszukiwania';
    $labels['mailbox_headers_in_results'] = 'Wyświetl nazwę folderu w rzędzie';
    $labels['mailbox_info_in_results'] = 'Wyświetl nazwę folderu w kolumnie';
    $labels['display_in_messagemenu'] = 'w menu wiadomości';
    $labels['display_in_toolbar'] = 'jako przycisk';
    $labels['show_advanced_search'] = 'Pokaż zaawansowane wyszukiwanie';
    $labels['saved_searches'] = 'Zachowane wyszukiwania';
    $labels['save_the_search'] = 'Zachowaj to wyszukiwanie';
    $labels['has_been_saved'] = 'zostało zachowane';
    $labels['deletesearch'] = 'Usuń wyszukiwanie';
    $labels['has_been_deleted'] = 'zostało usunięte';
    $labels['cancel'] = 'Anuluj';
    $labels['delete'] = 'Usuń';
    $labels['Common'] = 'Zwykłe';
    $labels['Addresses'] = 'Adresy';
    $labels['Dates'] = 'Daty';
    $labels['Flags'] = 'Flagi';
    $labels['Other'] = 'Inne';
    $labels['ANSWERED'] = 'Odpowiedziano';
    $labels['BCC'] = 'Bcc';
    $labels['BEFORE'] = 'Przed datą';
    $labels['CC'] = 'Cc';
    $labels['DELETED'] = 'Skasowana';
    $labels['DRAFT'] = 'Kopia robocza';
    $labels['FLAGGED'] = 'Oznaczona';
    $labels['KEYWORD'] = 'Słowo kluczowe';
    $labels['LARGER'] = 'Większe od';
    $labels['BODY'] = 'Treść wiadomości';
    $labels['ON'] = 'W dacie';
    $labels['SEEN'] = 'Przeczytana';
    $labels['SENTBEFORE'] = 'Wysłany przed datą';
    $labels['HEADER FROM'] = 'Od';
    $labels['SENTON'] = 'Wysłany w dacie';
    $labels['SENTSINCE'] = 'Wysłane od daty';
    $labels['HEADER TO'] = 'Do';
    $labels['SINCE'] = 'Od daty';
    $labels['SMALLER'] = 'Mniejsze od';
    $labels['SUBJECT'] = 'Temat zawiera';
    $labels['name'] = 'Nazwa';
    $labels['save'] = 'Zachowaj';
    $labels['mbox'] = 'Folder';

**Comment by FireFoxIXI** [comment]
@dzikus Thanks for your contribution, this has been added.

For future reference do a fork and pull request.
