### ISSUE TITLE
Keyboard input makes it back through to roundcube even with the advanced_search window open

### ISSUE THREAD

**Issue by atEverychance** [GMS-SA/roundcube-advanced-search#2]
Can this plugin prevent keyboard input from being passed through to the site? Or, possibly disable the keyboard_shortcuts plugin while the advanced_search box is open?

This is an issue as with the keyboard_shortcuts plugin enabled, if I type an "a" as part of my advanced_search value, and then a "d" as part of that search value, all the messages from the folder I am in are deleted.

Open to any other solutions too, but at this point the advanced_search plugin and the keyboard_shortcut plugin cannot be run at the same time. :(

Thanks!

**Comment by gms-chris** [comment]
Fixed by preventing propagation of the keypress event
