### ISSUE TITLE
Search error: UID SEARCH: parse error: zero-length content

### ISSUE THREAD

**Issue by krambiorix** [GMS-SA/roundcube-advanced-search#3]
Hi guys, 

i tried your plugin but always i get an error: UID SEARCH: parse error: zero-length content

Thx

**Comment by m3ph15t0** [comment]
Hi,

Which IMAP server are you using ?

On 04/10/2013 11:55 AM, krambiorix wrote:

> Hi guys,
> 
> i tried your plugin but always i get an error: UID SEARCH: parse 
> error: zero-length content
> 
> Thx
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/GMS-SA/roundcube-advanced-search/issues/3.

## 

Claude Wilwert

**Comment by krambiorix** [comment]
Hello,
i'm using zimbra.

**Comment by krambiorix** [comment]
Solved: 

UID SEARCH RETURN (ALL) UNDELETED  ALL
There were two spaces between UNDELETED and ALL . 
Zimbra doesn't accept that.
