### ISSUE TITLE
All folders search not working properly

### ISSUE THREAD

**Issue by adamjeelife** [GMS-SA/roundcube-advanced-search#4]
All folders search not working properly, its showing emails but on double click its failed to open the email and display message "Could not load message from server".
If default inbox page is open and I try to search email in all folders which is not in inbox its display above mentioned error "Could not load message from server". 
I will be very thankful to you if you resolve this issue.

**Comment by gms-chris** [comment]
We are aware of this problem and are looking into how to resolve it.

This core issue is that the Roundcube JavaScript overwrites the target folder with the current folder and the message is then not found. There is a good chunk of the core code that simply does not work with the concept of a message list displaying the content from multiple folders.

**Comment by adamjeelife** [comment]
Thanks for your prompt response. I also use Message Label plugin for roundcube that filter emails from all folders but have a limitation to search with limited fields like( Subject, From , To and cc). May be this information will help you to resolve this issue.
Download linkhttps://github.com/umount/message_label
Regards,
Muhammad Faisal
Date: Wed, 29 May 2013 02:57:41 -0700

**Comment by adamjeelife** [comment]
Thanks for your prompt response. I also use Message Label plugin for roundcube that filter emails from all folders but have a limitation to search with limited fields like( Subject, From , To and cc). May be this information will help you to resolve this issue.

Download link
https://github.com/umount/message_label

**Comment by gms-chris** [comment]
Thanks for the link.
It looks like you can produce the same error in this plugin in a different way:
- create a label that searches multiple folders
- enter the label 'mailbox'
- perform an open in new tab/window on a mail that is not in the last mailbox of your mailbox list

Am working on a fix to the advanced_search. Similar solution to the above. You need to overwrite the interfaces idea of what is the current mailbox.

There will still be issues when there are conflicting uid's from different mailboxes. This can be the case. The RoundCube message list does not have any way of dealing with this as far as I can see.

**Comment by atEverychance** [comment]
@gms-chris Really appreciate your working to resolve the All Folders search bug - Is there anywhere I can donate to a beer fund to help? :)

**Comment by atEverychance** [comment]
@gms-chris how goes the All Folders results fix efforts? anywhere I can donate to help? really appreciate your working at it! thank you!

**Comment by gms-chris** [comment]
I have one part working, that is the display of the correct message. There is still the outstanding issue of conflicting UIDs in the list. I am not sure I wish to do what was done in the message_label plugin here. Looking at an alternative.

**Comment by atEverychance** [comment]
@gms-chris awesome! thanks again. let me know if you need help testing or anything.

**Comment by atEverychance** [comment]
@gms-chris don't mean to press too hard, really appreciate any time you can dedicate to this, but any luck with this All Folders search fix? one of my clients keeps asking about it. 

thanks again.

**Comment by gms-chris** [comment]
Sorry for the delay. I have a works-for-me implementation that is not as tested as I would like.
We have had other work that has been more pressing and not really time to work on this.
I might release a point-release just so that it should 'work more' for now.
I have had to revert to a style that some other plugins use. It is ugly and you cannot perform any 'right-click' (open in new tab/window) style operations. This does seem to be the only way to work however, due to message ID conflicts between folders and the message ID being the _only_ value that RC uses to identify a message in the message list.
Not well tested are various operations:
- move
- delete
  These may well need additional code to make them work as expected.

**Comment by atEverychance** [comment]
yeah, will take a point release, that'd be great! thanks @gms-chris really appreciate it!

**Comment by gms-chris** [comment]
Initial fix pushed to master

**Comment by adamjeelife** [comment]
Thank you so much gms-chris

**Comment by FireFoxIXI** [comment]
Hello, we pushed a new version to stable that should solve this issues.

We tested:
- Moving messages
- Deleting messages
- Editing draft messages
- Forwarding multiple messages
- Marking messages
- Selecting messages

Please give it a try and tell us if this works now as expected.

**Comment by gms-chris** [comment]
No response. Issues should all be addressed. Closing

**Comment by cpdn** [comment]
Hi.
Same problem with browsing INBOX after search. 
Searching fine. Moving, deleting, etc. fine too.
Click message in INBOX folder - "Could not load message from server"
It's in INBOX folder only. Other folders -OK.
Logout - login - INBOX folder work fine again.

advanced_search ver: 2.1.6
roundcube ver: 1.0.1
