### ISSUE TITLE
Only all folder search works. Single folder search always throws "Mailbox doesn't exist"

### ISSUE THREAD

**Issue by darkmattercoder** [GMS-SA/roundcube-advanced-search#5]
Hi 

I just tested the plugin. When I perform a single folder search, a message pops up which tells me:

"Server Error: SELECT: Mailbox not found xx"

Where xx stands for the mailbox number in the order of the list. All folder search works, although the results are limited to 100 or whatever you select in roundcube for the number of messages to display.

**Comment by gms-chris** [comment]
I just tried to emulate this on the current release.
This is true if:
- you choose advanced search in one folder and search in another.

This is due to the fact that roundcube over-writes the mailbox with the 'current' selected folder, outside the plugin. This will be resolved in the next release.

**Comment by gms-chris** [comment]
Initial fix pushed to master

**Comment by FireFoxIXI** [comment]
We pushed a new version that should have fixed this issue.
