### ISSUE TITLE
new config option - target_menu is great, but unable to choose toolbar

### ISSUE THREAD

**Issue by atEverychance** [GMS-SA/roundcube-advanced-search#6]
Love the new target_menu config option. That will be really great, many users clamouring for easier access to the Advanced Search functionality. 

However, choosing "toolbar" for the target_menu breaks the Toolbar menu. I tried adjusting the styles.css file in both the larry and classic themes, but could not find the appropriate settings, and am concerned it will take more than CSS tweaks.

What can we do to make "toolbar" one of the options for target_menu config option? There is already a "search" icon included in the buttons.png file.

Again, REALLY appreciate all your efforts with this!

**Comment by FireFoxIXI** [comment]
Hello, we pushed a new version to stable that solves this issue. 

In addition this preference is now user configurable via:

Settings -> Preferences -> Advanced search

Hope this does what you expected.
