### ISSUE TITLE
Enhancement: Option to save and reuse searches

### ISSUE THREAD

**Issue by tpokorra** [GMS-SA/roundcube-advanced-search#7]
I am wondering how much work it would be to be able to save a search, and to reuse it later?
Next step would be to use the searches as virtual folders, similar to Horde.

**Comment by gms-chris** [comment]
We are in the process of making some substantial changes to this plugin. This is mainly to deal with Roundcubes shortcomings when dealing with multiple folders.

I see you have already started working on an implementation for this idea. Please be aware that this might need some major reworking after the coming update.

**Comment by tpokorra** [comment]
@gms-chris: thanks for your work on the plugin.
I have updated my patch to version 2.0.0 of the advanced-search plugin.

**Comment by FireFoxIXI** [comment]
@tpokorra Thank you for your proposed enhancement. 
We now fully integrated the option to save, load, edit and delete searches.
Please have a look and tell us  if this works for you.

**Comment by tpokorra** [comment]
@FireFoxIXI: thanks for that!
I like it!

Small issues:
- when I click on saved searches, and the list drops down, also the topline drops down, the one that shows the about link and the username.
- when I delete a search, the search is still in the dropdown box of saved searches, until I reload the page with F5
- there is an issue with the first saved search (delete all searches first and reload the page, to reproduce this). when I save the first search, close the search window, open it again, the search is in the saved searches dropdown. I save a new search, but the first search is not displayed anymore, until I reload the page. after that, new searches are added fine to the dropdown.

**Comment by FireFoxIXI** [comment]
@tpokorra Thank you for your feedback.
- The deletion not working properly was an omission on my end, the search to delete from the select was still hardcoded.
- The other 2 issues are probably due to the select being in the titlebar of the dialog, I will have to dig deeper in to this.

**Comment by tpokorra** [comment]
Thank you, I have tested it, and it works now fine!
