### ISSUE TITLE
roundcube 1.0 RC broke advanced search

### ISSUE THREAD

**Issue by RavenB** [GMS-SA/roundcube-advanced-search#8]
Hi,

Roundcube 1.0 RC broke advanced search.

Advanced search no longer works. When clicking on hourglass adv. search popup does NOT appear or when as drop down menu advanced search remains greyed out.
The issue sonly occur since 1.0 RC just released.
Can we have a fix  ?:) (even a quickfix would be great)

regards,

**Comment by gms-chris** [comment]
New version should fix issue.
